server:
  port: 8080
  netty:
    max-header-size: 32KB

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/events/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/bookings/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# same secret as the User Service (which issues the tokens)
jwt:
  secret: ticket-booking-system-swe4602-secret-key-2026
